replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/notification-service
  tag: "3.0.2"
  pullPolicy: IfNotPresent
  pullSecret: dmirandam-regcred   

service:
  port: 50054
  targetPort: 50054

resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 256Mi

env:                      
  MAILGUN_DOMAIN: sandbox7c56f2d3ea2b4ad699f6b59a31530d0d.mailgun.org
  MAILGUN_API_KEY: ac09d9d15feccfb574f321ea9d6a63df-5bb33252-267ad3b3
  SENDER_EMAIL: postmaster@sandbox7c56f2d3ea2b4ad699f6b59a31530d0d.mailgun.org
  AMQP_URL: amqp://notifier:G8Xg2VU84l@notifications-cluster.rabbitmq.svc.cluster.local:5672/notifications
config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }

autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60   
      selectPolicy: Max                
      policies:
      - type: Percent
        value: 50                      
        periodSeconds: 30              
      - type: Pods
        value: 2                       
        periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30   
      selectPolicy: Max
      policies:
      - type: Percent
        value: 100                     
        periodSeconds: 15
      - type: Pods
        value: 3                       
        periodSeconds: 15