replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/api-gateway
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  pullSecret: dmirandam-regcred   

service:
  port: 80
  targetPort: 8080

env:                      
  KEY: "value"
  USER_PRODUCT_SERVICE_GRPC_HOST: "user-product-service:50052"
  AUTH_SERVICE_GRPC_HOST: "auth-service:50053"
  TRANSACTION_SERVICE_GRPC_HOST: "transaction-service:50051"

config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }


autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75 