replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/frontend
  tag: "3.0.4"
  pullPolicy: Always
  pullSecret: dmirandam-regcred   

service:
  port: 80
  targetPort: 3000

env:                      
  NEXT_PUBLIC_API_URL: api-gateway:80

resources:
  requests:
    cpu: 75m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 256Mi

config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }

autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60   
      selectPolicy: Max                
      policies:
      - type: Percent
        value: 50                      
        periodSeconds: 30              
      - type: Pods
        value: 2                       
        periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30   
      selectPolicy: Max
      policies:
      - type: Percent
        value: 100                     
        periodSeconds: 15
      - type: Pods
        value: 3                       
        periodSeconds: 15