replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/frontend
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  pullSecret: dmirandam-regcred   

service:
  port: 80
  targetPort: 3000

env:                      
  NEXT_PUBLIC_API_URL: 'http://api_gateway'

config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }

autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75 