replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/frontend
  tag: "3.0.4"
  pullPolicy: Always
  pullSecret: dmirandam-regcred   

service:
  port: 80
  targetPort: 3000

env:                      
  NEXT_PUBLIC_API_URL: api-gateway:80

config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }

autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75 
