apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-service.name" . }}-config
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: |-
{{ $val | indent 4 }}
{{- end }}
