apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notification-service.name" . }}
  labels: {{- include "notification-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels: {{- include "notification-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "notification-service.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
          volumeMounts:
            - name: app-config
              mountPath: /data/config
      volumes:
        - name: app-config
          configMap:
            name: {{ include "notification-service.name" . }}-config