apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-service.name" . }}
  labels: {{- include "auth-service.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "auth-service.selectorLabels" . | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
