replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/transaction-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  pullSecret: dmirandam-regcred   

service:
  port: 50051
  targetPort: 50051

env:                      
  KEY: "value"


config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }


autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75 