replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/auth-service
  tag: "3.0.1"
  pullPolicy: IfNotPresent
  pullSecret: dmirandam-regcred   

service:
  port: 50053
  targetPort: 50053

env:                      
  MONGODB_URI: "mongodb+srv://dsmirandama:1UDV2oVZYjESTftz@nova-auth.mwonkib.mongodb.net/?retryWrites=true&w=majority&appName=Nova-Auth"
  MONGODB_DATABASE: "Nova-Auth"
config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }
autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75 
