replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/auth-service
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  pullSecret: dmirandam-regcred   

service:
  port: 50053
  targetPort: 50053

env:                      
  MONGODB_URI: "mongodb://admin:password123@mongodb:27017/auth_db?authSource=admin"
  MONGODB_DATABASE: "auth_db"

config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }


autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75 