replicaCount: 2

image:
  repository: registry.dmirandam.com/nova/user-product
  tag: "1.0.0"
  pullPolicy: IfNotPresent
  pullSecret: dmirandam-regcred   

service:
  port: 50052
  targetPort: 50052

env:                      
  KEY: "value"
  DB_HOST: nova.enpoint.us-east-1.rds.amazonaws.com
  DB_PORT: 5432
  DB_USER: master
  DB_PASSWORD: password123
  DB_NAME: postgres

config:                    
  appsettings.json: |
    {
      "AppSettings": {
        "FeatureX": true
      }
    }

autoscaling:
  enabled: true         
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80     
  targetMemoryUtilizationPercentage: 75 