apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: frontend-gateway
  namespace: nova
spec:
  selector:
    istio: ingress
  servers:
    - hosts:
        - nova.dmirandam.com
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: nova-crt