apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-vs
  namespace: nova
spec:
  gateways:
    - frontend-gateway
  hosts:
    - nova.dmirandam.com
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ include "frontend.name" . }}
            port:
              number: 80